# Name
DE_NOVO = "stacks/de_novo/"
COMMAND = "denovo_map.pl"

# STACKS de_novo parameters
BATCH_ID = 'BATCH_ID'
OUTPUT_PATH = 'OUTPUT_PATH'
POPULATION_MAP = 'POPULATION_MAP'
CROSS_TYPE = 'CROSS_TYPE'
N_THREADS = 'N_THREADS'
EXE_PATH = 'EXE_PATH'
DRY_RUN = 'DRY_RUN'
HELP_MESSAGE = 'HELP_MESSAGE'
PARENTS_SEQUENCES_FILE = 'PARENTS_SEQUENCES_FILE'
PROGENY_SEQUENCES_FILE = 'PROGENY_SEQUENCES_FILE'
INDIVIDUAL_SEQUENCES_FILE = 'INDIVIDUAL_SEQUENCES_FILE'
SAMPLES_DIRECTORY = 'SAMPLES_DIRECTORY'
IDENTICAL_READS_FOR_STACK = 'IDENTICAL_READS_FOR_STACK'
MISMATCHES_IN_INDIVIDUAL = 'MISMATCHES_IN_INDIVIDUAL'
MISMATCHES_IN_CATALOG = 'MISMATCHES_IN_CATALOG'
ALLOW_GAPS = 'ALLOW_GAPS'
INDENTICAL_READS_FOR_STACK_PROGENY = 'INDENTICAL_READS_FOR_STACK_PROGENY'
MISMATCHES_IN_SECONDARY_READS = 'MISMATCHES_IN_SECONDARY_READS'
REMOVE_REPETITIVE_STACKS = 'REMOVE_REPETITIVE_STACKS'
DISABLE_HAPLOTYPES_FROM_SECONDARY = 'DISABLE_HAPLOTYPES_FROM_SECONDARY'
DATABASE_NAME = 'DATABASE_NAME'
DATABASE_DESCRIPTION = 'DATABASE_DESCRIPTION'
DISABLE_DATABASE = 'DISABLE_DATABASE'
STARTING_SAMPLE_ID = 'STARTING_SAMPLE_ID'
CREATE_DATABASE = 'CREATE_DATABASE'
OVERWRITE_DATABASE = 'OVERWRITE_DATABASE'
BOUND_LOW_USTACKS = 'BOUND_LOW_USTACKS'
BOUND_HIGH_USTACKS = 'BOUND_HIGH_USTACKS'
ALPHA_USTACKS = 'ALPHA_USTACKS'
PIPELINE_COMMAND = 'PIPELINE_COMMAND'

# Default keys (for verification during loading of default file)
# DEFAULT_KEYS = {BATCH_ID, OUTPUT_PATH, POPULATION_MAP, CROSS_TYPE,
#                 N_THREADS, EXE_PATH, DRY_RUN, HELP_MESSAGE,
#                 PARENTS_SEQUENCES_FILE, PROGENY_SEQUENCES_FILE,
#                 INDIVIDUAL_SEQUENCES_FILE, SAMPLES_DIRECTORY,
#                 IDENTICAL_READS_FOR_STACK, MISMATCHES_IN_INDIVIDUAL,
#                 MISMATCHES_IN_CATALOG, ALLOW_GAPS,
#                 INDENTICAL_READS_FOR_STACK_PROGENY,
#                 MISMATCHES_IN_SECONDARY_READS,
#                 REMOVE_REPETITIVE_STACKS,
#                 DISABLE_HAPLOTYPES_FROM_SECONDARY,
#                 DATABASE_NAME, DATABASE_DESCRIPTION,
#                 DISABLE_DATABASE, STARTING_SAMPLE_ID, CREATE_DATABASE,
#                 OVERWRITE_DATABASE, BOUND_LOW_USTACKS, BOUND_HIGH_USTACKS,
#                 ALPHA_USTACKS, PIPELINE_COMMAND}
